name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update package.json
        run: |
          echo "Updating package.json..."
          npm update --save-dev
          echo "Package.json is updated."

      - name: Build Docker image
        run: |
          echo "Building Docker image..."
          docker build -t my-image .
          echo "Docker image is built successfully."

      - name: Deploy to production
        run: |
          echo "Deploying to production..."
          npm install
          docker push my-image
